# app/rag/generator.py
import os
import requests

HF_API_TOKEN = os.getenv("HF_API_TOKEN")
HF_GENERATION_URL = "https://api-inference.huggingface.co/models/google/flan-t5-base"



headers = {
    "Authorization": f"Bearer {HF_API_TOKEN}",
    "Content-Type": "application/json"
}

def generate_answer(prompt, max_tokens=300):
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": max_tokens,
            "do_sample": False,
            "return_full_text": False
        }
    }

    response = requests.post(HF_GENERATION_URL, headers=headers, json=payload)
    response.raise_for_status()

    output = response.json()
    if isinstance(output, list) and "generated_text" in output[0]:
        return output[0]["generated_text"]
    else:
        return "⚠️ No response generated by the model."
